"""Export the scipy resample_poly filter taps to a C++ header.

tagodsp.distortion.clipper resamples with scipy.signal.resample_poly and a
kaiser beta 12 window. The C++ Oversampler must run the identical FIR to keep
golden-file parity, so the taps are exported here instead of reimplementing
scipy's kaiser design in C++.

For factor L this is exactly what resample_poly designs internally:
taps = firwin(2*10*L + 1, 1/L, window=("kaiser", 12.0)). The gain scaling by L
for the upsampling path happens at runtime in Oversampler.

Run with the tagodsp venv python:
    ~/Documents/tagodsp/.venv/bin/python scripts/gen_filter_taps.py
"""

import argparse
from pathlib import Path

from scipy.signal import firwin

FACTORS = (4, 8)
BETA = 12.0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "plugin/dsp/OversamplerTaps.h",
    )
    args = parser.parse_args()

    lines = [
        "// Generated by scripts/gen_filter_taps.py, do not edit by hand.",
        '// FIR taps identical to scipy.signal.resample_poly(window=("kaiser", 12.0))',
        "// as used by tagodsp.distortion.clipper.",
        "#pragma once",
        "",
        "namespace tagoclip::taps",
        "{",
    ]
    for L in FACTORS:
        h = firwin(2 * 10 * L + 1, 1.0 / L, window=("kaiser", BETA))
        lines.append(f"inline constexpr int numTaps{L}x = {len(h)};")
        lines.append(f"inline constexpr double taps{L}x[] = {{")
        for i in range(0, len(h), 4):
            chunk = ", ".join(repr(float(v)) for v in h[i : i + 4])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")
    lines.append("} // namespace tagoclip::taps")
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({', '.join(f'{L}x' for L in FACTORS)})")


if __name__ == "__main__":
    main()
